In [3]:
# Import the pandas library for data manipulation
import pandas as pd

# Define data as a dictionary
data = {
    'Name' : ['alice','bob','charlie'],
    'Age' : [25,30,35],
    'City' : ['New York','San Francisco','Los Angeles']
}

# Create a pandas DataFrame 'd' from the dictionary
d = pd.DataFrame(data)
# Print the DataFrame 'd'
print(d)

      Name  Age           City
0    alice   25       New York
1      bob   30  San Francisco
2  charlie   35    Los Angeles

In [6]:
# Display the DataFrame 'd'
display(d)

      Name  Age           City
0    alice   25       New York
1      bob   30  San Francisco
2  charlie   35    Los Angeles

In [8]:
# Define lists for Name, Age, and City
ls = ['alice','bob','charlie']
age = [25,30,35]
city = ['New York','San Francisco','Los Angeles']

# Create a DataFrame 'df' with 'Name' column from 'ls'
df = pd.DataFrame(ls,columns=['Name'])
# Add 'Age' column to 'df'
df['Age'] = age
# Add 'City' column to 'df'
df['City'] = city

# Print and display the DataFrame 'df'
print(df)
display(df)

      Name  Age           City
0    alice   25       New York
1      bob   30  San Francisco
2  charlie   35    Los Angeles

      Name  Age           City
0    alice   25       New York
1      bob   30  San Francisco
2  charlie   35    Los Angeles

In [10]:
# Define data as a dictionary
data = {
    'Name' : ['alice','bob','charlie'],
    'Age' : [25,30,35],
    'City' : ['New York','San Francisco','Los Angeles']
}
# Create a pandas DataFrame 'df' from the dictionary
df = pd.DataFrame(data)
# Display the DataFrame 'df'
display(df)

      Name  Age           City
0    alice   25       New York
1      bob   30  San Francisco
2  charlie   35    Los Angeles

In [13]:
# Select and print specific rows (0 and 1) from DataFrame 'df' using .loc
#print(df.loc[1])
print(df.loc[[0,1]])

    Name  Age           City
0  alice   25       New York
1    bob   30  San Francisco

In [16]:
# Import 'A' from 're' (though 'A' is not used here and re is not relevant to DataFrame creation)
from re import A

# Create a DataFrame 'df' with custom string indices 'A', 'B', 'C'
df = pd.DataFrame(data, index=['A','B','C'])
# Select and print the row with index 'A'
print(df.loc['A'])
# Display the DataFrame 'df'
display(df)

Name       alice
Age           25
City    New York
Name: A, dtype: object

      Name  Age           City
A    alice   25       New York
B      bob   30  San Francisco
C  charlie   35    Los Angeles

In [24]:
# Import the 'files' module from google.colab to handle file operations
from google.colab import files

# Read 'transactions.csv' into a pandas DataFrame 'df'
df = pd.read_csv('transactions.csv')
# Display the first 5 rows of the DataFrame
display(df.head())
# Display the last 5 rows of the DataFrame
display(df.tail())

,amount,time_gap_minutes,location_change,device_change,foreign_transaction,fraud
0,10211.44,1399,1,0,1,1
1,20861.09,483,0,1,1,0
2,6160.72,346,0,1,1,0
3,2575.51,1248,0,1,0,1
4,10529.16,1120,0,0,0,1

,amount,time_gap_minutes,location_change,device_change,foreign_transaction,fraud
395,10372.41,190,1,0,0,1
396,8344.79,1051,0,0,1,1
397,38617.91,1178,0,1,1,0
398,12139.15,424,1,0,0,0
399,47748.91,849,0,0,0,0

In [25]:
# Access and display the 'time_gap_minutes' column from DataFrame 'df'
df['time_gap_minutes']

0      1399
1       483
2       346
3      1248
4      1120
       ...
395     190
396    1051
397    1178
398     424
399     849
Name: time_gap_minutes, Length: 400, dtype: int64

In [28]:
# Read 'transactions.csv' into a pandas DataFrame 'ab'
ab = pd.read_csv('transactions.csv')
# Display the DataFrame 'ab'
display(ab)

,amount,time_gap_minutes,location_change,device_change,foreign_transaction,fraud
0,10211.44,1399,1,0,1,1
1,20861.09,483,0,1,1,0
2,6160.72,346,0,1,1,0
3,2575.51,1248,0,1,0,1
4,10529.16,1120,0,0,0,1
...,...,...,...,...,...,...
395,10372.41,190,1,0,0,1
396,8344.79,1051,0,0,1,1
397,38617.91,1178,0,1,1,0
398,12139.15,424,1,0,0,0
399,47748.91,849,0,0,0,0

In [31]:
# Define data as a dictionary
data = {
    'Name' : ['alice','bob','charlie'],
    'Age' : [25,30,35],
    'City' : ['New York','San Francisco','Los Angeles']
}
# Create a pandas DataFrame 'df' from the dictionary
df = pd.DataFrame(data)
# Save the DataFrame to 'data.csv' without writing the index
df.to_csv('data.csv', index=False)
# Download the 'data.csv' file
files.download('data.csv')

# Read 'data.csv' back into a DataFrame 'df'
df = pd.read_csv('data.csv')
# Display the DataFrame 'df'
display(df)

      Name  Age           City
0    alice   25       New York
1      bob   30  San Francisco
2  charlie   35    Los Angeles

In [35]:
# Select and store specific rows (1, 0, 6, 8, 4) from DataFrame 'ab' into 'dr' using .loc
dr = ab.loc[[1,0,6,8,4]]
# Print the selected rows
print(dr)
# Display the selected rows
display(dr)

     amount  time_gap_minutes  location_change  device_change  \
1  20861.09               483                0              1
0  10211.44              1399                1              0
6  37134.68               939                1              1
8  32463.44              1092                0              1
4  10529.16              1120                0              0

   foreign_transaction  fraud
1                    1      0
0                    1      1
6                    0      0
8                    1      1
4                    0      1

,amount,time_gap_minutes,location_change,device_change,foreign_transaction,fraud
1,20861.09,483,0,1,1,0
0,10211.44,1399,1,0,1,1
6,37134.68,939,1,1,0,0
8,32463.44,1092,0,1,1,1
4,10529.16,1120,0,0,0,1

In [37]:
# Create a dummy column 'dummy_column' with a range of values
ab['dummy_column'] = range(len(ab))

# Insert a new column 'new_column_inserted' at index 1 (second position)
# The values are twice the 'dummy_column' values
ab.insert(1, 'new_column_inserted', ab['dummy_column'] * 2)
# Display the head of the modified DataFrame 'ab'
display(ab.head())

,amount,new_column_inserted,time_gap_minutes,location_change,device_change,foreign_transaction,fraud,dummy_column
0,10211.44,0,1399,1,0,1,1,0
1,20861.09,2,483,0,1,1,0,1
2,6160.72,4,346,0,1,1,0,2
3,2575.51,6,1248,0,1,0,1,3
4,10529.16,8,1120,0,0,0,1,4

In [36]:
# Use assign to create new columns 'amount_category' and 'time_category'
# 'amount_category' categorizes 'amount' into 'Low', 'Medium', 'High' based on bins
# 'time_category' categorizes 'time_gap_minutes' into 'Short', 'Medium', 'Long' based on bins

ab_assigned = ab.assign(
    amount_category=lambda x: pd.cut(x['amount'], bins=[0, 10000, 20000, 50000], labels=['Low', 'Medium', 'High']),
    time_category=lambda x: pd.cut(x['time_gap_minutes'], bins=[0, 500, 1000, 1500], labels=['Short', 'Medium', 'Long'])
)
# Display the head of the new DataFrame 'ab_assigned' with the new columns
display(ab_assigned.head())

,amount,time_gap_minutes,location_change,device_change,foreign_transaction,fraud,amount_category,time_category
0,10211.44,1399,1,0,1,1,Medium,Long
1,20861.09,483,0,1,1,0,High,Short
2,6160.72,346,0,1,1,0,Low,Short
3,2575.51,1248,0,1,0,1,Low,Long
4,10529.16,1120,0,0,0,1,Medium,Long

In [ ]:
# This cell is currently empty.