In [1]:
import pandas as pd
import numpy as np

# Create a dummy students.csv file for tasks 6-10
students_data = {
    'ID': [101, 102, 103, 104, 105],
    'Name': ['Ravi', 'Priya', 'Rahul', 'Sneha', 'Anil'],
    'Age': [20, 21, 20, 22, 21],
    'Department': ['CSE', 'ECE', 'CSE', 'IT', 'EEE'],
    'Marks': [85, 90, 78, 95, 88]
}
df_students_csv = pd.DataFrame(students_data)
df_students_csv.to_csv('students.csv', index=False)
print("Created students.csv")

Created students.csv

In [2]:
monthly_sales = pd.Series([10000, 12000, 11000, 15000], index=['Jan', 'Feb', 'Mar', 'Apr'])
monthly_expenses = pd.Series([7000, 8500, 7500, 9000], index=['Jan', 'Feb', 'Mar', 'Apr'])

monthly_profit = monthly_sales - monthly_expenses

print("Monthly Sales:")
display(monthly_sales)
print("\nMonthly Expenses:")
display(monthly_expenses)
print("\nMonthly Profit:")
display(monthly_profit)

Monthly Sales:

Jan    10000
Feb    12000
Mar    11000
Apr    15000
dtype: int64

Monthly Expenses:

Jan    7000
Feb    8500
Mar    7500
Apr    9000
dtype: int64

Monthly Profit:

Jan    3000
Feb    3500
Mar    3500
Apr    6000
dtype: int64

In [3]:
student_names = pd.Series(['Alice', 'Bob', 'Charlie', 'David'], index=[101, 102, 103, 104])
print("Student Names with Roll Numbers as Indices:")
display(student_names)

Student Names with Roll Numbers as Indices:

101      Alice
102        Bob
103    Charlie
104      David
dtype: object

In [4]:
student_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [18, 19, 18],
    'Marks': [90, 85, 92]
})
print("Student DataFrame:")
display(student_df)

Student DataFrame:

      Name  Age  Marks
0    Alice   18     90
1      Bob   19     85
2  Charlie   18     92

In [5]:
df = pd.read_csv('students.csv')
print("DataFrame from students.csv:")
display(df)

DataFrame from students.csv:

    ID   Name  Age Department  Marks
0  101   Ravi   20        CSE     85
1  102  Priya   21        ECE     90
2  103  Rahul   20        CSE     78
3  104  Sneha   22         IT     95
4  105   Anil   21        EEE     88

In [6]:
print("First five rows:")
display(df.head())
print("\nShape:", df.shape)
print("\nColumn Names:", df.columns.tolist())

First five rows:

    ID   Name  Age Department  Marks
0  101   Ravi   20        CSE     85
1  102  Priya   21        ECE     90
2  103  Rahul   20        CSE     78
3  104  Sneha   22         IT     95
4  105   Anil   21        EEE     88

Shape: (5, 5)

Column Names: ['ID', 'Name', 'Age', 'Department', 'Marks']

In [7]:
cse_high_scorers = df[(df['Department'] == 'CSE') & (df['Marks'] > 80)]
print("Students from CSE with > 80 marks:")
display(cse_high_scorers)

Students from CSE with > 80 marks:

    ID  Name  Age Department  Marks
0  101  Ravi   20        CSE     85

In [8]:
high_scorers = df[df['Marks'] > 80]
print("Students with > 80 marks:")
display(high_scorers)

Students with > 80 marks:

    ID   Name  Age Department  Marks
0  101   Ravi   20        CSE     85
1  102  Priya   21        ECE     90
3  104  Sneha   22         IT     95
4  105   Anil   21        EEE     88

In [9]:
df_result = pd.read_csv('students.csv')
df_result['Result'] = np.where(df_result['Marks'] >= 40, 'Pass', 'Fail')
df_result.to_csv('result.csv', index=False)
print("DataFrame with 'Result' column saved to result.csv:")
display(df_result)

DataFrame with 'Result' column saved to result.csv:

    ID   Name  Age Department  Marks Result
0  101   Ravi   20        CSE     85   Pass
1  102  Priya   21        ECE     90   Pass
2  103  Rahul   20        CSE     78   Pass
3  104  Sneha   22         IT     95   Pass
4  105   Anil   21        EEE     88   Pass

In [10]:
df_grade = pd.read_csv('students.csv')

def assign_grade(marks):
    if marks >= 90:
        return 'A'
    elif marks >= 75:
        return 'B'
    elif marks >= 50:
        return 'C'
    else:
        return 'D'

df_grade['Grade'] = df_grade['Marks'].apply(assign_grade)

print("DataFrame with 'Grade' column:")
display(df_grade)

print("\nNumber of students in each grade:")
display(df_grade['Grade'].value_counts().sort_index())

print("\nDepartment-wise average marks:")
display(df_grade.groupby('Department')['Marks'].mean())

overall_average_marks = df_grade['Marks'].mean()
students_above_overall_average = df_grade[df_grade['Marks'] > overall_average_marks]
print(f"\nStudents whose marks are above the overall average ({overall_average_marks:.2f}):")
display(students_above_overall_average)

DataFrame with 'Grade' column:

    ID   Name  Age Department  Marks Grade
0  101   Ravi   20        CSE     85     B
1  102  Priya   21        ECE     90     A
2  103  Rahul   20        CSE     78     B
3  104  Sneha   22         IT     95     A
4  105   Anil   21        EEE     88     B

Number of students in each grade:

Grade
A    2
B    3
Name: count, dtype: int64

Department-wise average marks:

Department
CSE    81.5
ECE    90.0
EEE    88.0
IT     95.0
Name: Marks, dtype: float64

Students whose marks are above the overall average (87.20):

    ID   Name  Age Department  Marks Grade
1  102  Priya   21        ECE     90     A
3  104  Sneha   22         IT     95     A
4  105   Anil   21        EEE     88     B

In [11]:
department_stats = df.groupby('Department')['Marks'].agg(['max', 'min', 'mean'])
print("Maximum, Minimum, and Average Marks for each department:")
display(department_stats)

Maximum, Minimum, and Average Marks for each department:

            max  min  mean
Department
CSE          85   78  81.5
ECE          90   90  90.0
EEE          88   88  88.0
IT           95   95  95.0